create database IT_Company;
use IT_Company;
create table Employee_Details(Emp_ID int primary key, Emp_Name varchar(30), Department varchar(20), City varchar(15), Salary int, Experience int);
insert into Employee_Details values(101,"Amit","HR","Lucknow",30000,2), (102,"priya","IT","Delhi",50000,4), (103,"Rahul","IT","Lucknow",55000,5),
(104,"Neha","sales","Kanpur",35000,3), (105,"Karan","HR","Delhi",32000,2), (106,"Simran","Sales","Lucknow",45000,6), (107,"Arjun","IT","Kanpur",60000,7),
(108,"Pooja","HR","Lucknow",28000,1), (109,"Riya","Sales","Delhi",40000,4), (110,"Mohit","IT","Lucknow",65000,8);
select * from Employee_Details;
select Emp_Name from Employee_Details;
select Emp_ID, Salary from Employee_Details;
select Salary>=40000 from Employee_Details;
select * from Employee_Details where Department="IT";
select * from Employee_Details order by Salary desc;
select count(Emp_ID) from Employee_Details;
select sum(Salary) from Employee_Details;
select avg(Salary) from Employee_Details;
select max(Salary) from Employee_Details;
select min(Salary) from Employee_Details;
select Department, count(*) from Employee_Details group by Department;
select Department, avg(Salary) from Employee_Details group by Department;
select Department, sum(Salary) from Employee_Details group by Department;
select City, count(*) from Employee_Details Group by City;
select Department, count(*) from Employee_Details group by Department having count(*)>2;
select Department, avg(Salary>=40000) from Employee_Details group by Department;
select * from Employee_Details order by Salary asc;
select * from Employee_Details order by Experience desc;
select Department from Employee_Details order by Department asc;
select Department, avg(Salary) from Employee_Details group by Department order by avg(Salary) desc;
select Emp_Name, Salary from Employee_Details where Salary=(Select max(Salary) from Employee_Details);
select avg(Salary) from Employee_Details where Department="IT";
select sum(Salary) from Employee_Details where city="Lucknow";
select count(*) from Employee_Details where Experience>=5;
select Department, avg(Salary) from Employee_Details group by Department order by avg(Salary) desc limit 1;